- hosts: localhost
  connection: local
  vars:
    - appliancelist: "{{ groups['sns-appliances'] }}"

  tasks:
    - include: sns-property-tasks.yaml target="{{ item }}"
      with_items: "{{ appliancelist }}"
